site_name: Testing mkdocs
site_description: Doing stuff
site_author: TheEpicTwin
site_url: https://twin1twin2.github.io/test_mkdocs_deploy/

nav:
  - Home: index.md
  - Stuff: stuff.md

theme:
  name: material
  palette:
    primary: red